version: "3.9"

services:
  email-service:
    build: .
    env_file:
      - ./.env
    ports:
      - "8081:8080"
    environment:
      - SPRING_MAIL_HOST:${MAIL_HOST}
      - SPRING_MAIL_PORT:${MAIL_PORT}
      - SPRING_MAIL_USERNAME:${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD:${MAIL_PASSWORD}
      - ES_ADDRESS:elasticsearch:9200
      - KAFKA_ADDRESS:kafka:9092
    depends_on:
      - elasticsearch
      - kafka
#      elasticsearch:
#        condition: service_healthy
    restart: on-failure
    networks:
      - my-network

  elasticsearch:
    image: elasticsearch:8.6.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
#    healthcheck:
#      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
#      interval: 30s
#      timeout: 10s
#      retries: 50
    networks:
      - my-network

  kibana:
    image: kibana:8.6.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - my-network

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - my-network

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
